#! /bin/sh

sxhkd &
#xfce4-panel &
nm-applet &

bspc monitor eDP1 -d term chrome code IV V VI VII com music
bspc monitor DP2 -d VGA1 

bspc config border_width         2
bspc config window_gap          15
bspc config top_padding         21

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a Spotify desktop='^9'
bspc rule -a Slack desktop='^8'
bspc rule -a libreoffice desktop='^4'

compton --config /home/torje/.config/compton.conf --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc -b &
syndaemon -i 1 -K d &
sh ~/.fehbg &
synclient HorizEdgeScroll=1 VertEdgeScroll=1 VertScrollDelta=-111 & 

setxkbmap us &

wmname LG3D &

spotify &

google-chrome &

slack &

xautolock -time 10 -locker "/usr/local/bin/lock -p" -detectsleep & 

killall -q notify-osd &
dunst -config ~/.config/dunstrc &
dropbox start &

$HOME/.config/polybar/launch.sh &

$HOME/.config/bspwm/moveWindow.sh &
